# Generated by Django 6.0.2 on 2026-02-17 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
